---
- name: Set up SSH on Raspberry Pi
  hosts: raspberry_pi
  become: yes
  tasks:
    - name: Install OpenSSH server
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Ensure SSH service is running
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Check if SSH key already exists
      stat:
        path: "/home/{{ pi_username }}/.ssh/id_rsa.pub"
      register: ssh_key

    - name: Generate SSH key pair
      user:
        name: "{{ pi_username }}"
        generate_ssh_key: yes
        ssh_key_file: "/home/{{ pi_username }}/.ssh/id_rsa"
      when: not ssh_key.stat.exists

    - name: Create .ssh directory
      file:
        path: "/home/{{ pi_username }}/.ssh"
        state: directory
        mode: "0700"
        owner: "{{ pi_username }}"
        group: "{{ pi_username }}"

    - name: Copy public key to authorized_keys
      authorized_key:
        user: "{{ pi_username }}"
        state: present
        key: "{{ lookup('file', '/home/{{ pi_username }}/.ssh/id_rsa.pub') }}"
